#:schema node_modules/wrangler/config-schema.json
name = "subli"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c1050451fd274f1e8567767fed366cc1" }
]

[assets]
directory = "./public"
